name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    
    steps:
    - uses: actions/checkout@main

    - uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.0.x

    - name: Build and test importando
      run: dotnet test -r win-x64 -c Release

    - name: Build and publish importando
      run: dotnet publish -r win-x64 -c Release

    - uses: actions/upload-artifact@main
      with:
        name: importando
        path: |
          importando\bin\x64\Release\net8.0-windows\win-x64\publish\importando.exe
          importando\bin\x64\Release\net8.0-windows\win-x64\publish\importando.pdb
